/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_BEACON_DATA_PB_H_INCLUDED
#define PB_BEACON_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _BeaconData { 
    int32_t aiden_us; 
    int32_t george_us; 
    int32_t aiden_rssi; 
    int32_t george_rssi; 
    int32_t thingy_rssi; 
    int32_t dongle_rssi; 
    int32_t time; 
    int32_t xander_us; 
    int32_t desmond_us; 
    int32_t xander_rssi; 
    int32_t desmond_rssi; 
    int32_t thingy2_rssi; 
    int32_t dongle2_rssi; 
} BeaconData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BeaconData_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BeaconData_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BeaconData_aiden_us_tag                  1
#define BeaconData_george_us_tag                 2
#define BeaconData_aiden_rssi_tag                3
#define BeaconData_george_rssi_tag               4
#define BeaconData_thingy_rssi_tag               5
#define BeaconData_dongle_rssi_tag               6
#define BeaconData_time_tag                      7
#define BeaconData_xander_us_tag                 8
#define BeaconData_desmond_us_tag                9
#define BeaconData_xander_rssi_tag               10
#define BeaconData_desmond_rssi_tag              11
#define BeaconData_thingy2_rssi_tag              12
#define BeaconData_dongle2_rssi_tag              13

/* Struct field encoding specification for nanopb */
#define BeaconData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    aiden_us,          1) \
X(a, STATIC,   REQUIRED, INT32,    george_us,         2) \
X(a, STATIC,   REQUIRED, INT32,    aiden_rssi,        3) \
X(a, STATIC,   REQUIRED, INT32,    george_rssi,       4) \
X(a, STATIC,   REQUIRED, INT32,    thingy_rssi,       5) \
X(a, STATIC,   REQUIRED, INT32,    dongle_rssi,       6) \
X(a, STATIC,   REQUIRED, INT32,    time,              7) \
X(a, STATIC,   REQUIRED, INT32,    xander_us,         8) \
X(a, STATIC,   REQUIRED, INT32,    desmond_us,        9) \
X(a, STATIC,   REQUIRED, INT32,    xander_rssi,      10) \
X(a, STATIC,   REQUIRED, INT32,    desmond_rssi,     11) \
X(a, STATIC,   REQUIRED, INT32,    thingy2_rssi,     12) \
X(a, STATIC,   REQUIRED, INT32,    dongle2_rssi,     13)
#define BeaconData_CALLBACK NULL
#define BeaconData_DEFAULT NULL

extern const pb_msgdesc_t BeaconData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BeaconData_fields &BeaconData_msg

/* Maximum encoded size of messages (where known) */
#define BeaconData_size                          143

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
